### ISSUE TITLE
Python exception on OSX - dark mode?

### ISSUE THREAD

**Issue by tristancollins** [AislerHQ/PushForKiCad#1]
I get the attached error when loading the PCB editor.

Kicad 6.0 on latest mac OSX

"AttributeError: 'PishForKiCadPlugin' object has no attribute 'dark_icon_file_name'"

Perhaps related to dark mode?
<img width="258" alt="Aisler_error" src="https://user-images.githubusercontent.com/8229525/148430077-4f910c18-a51c-4e84-952f-d3989560efd3.png">

The icon appears as a generic extension icon along the toolbar.

**Comment by tristancollins** [comment]
The search result from below indicate this may be a KiCAD issue?

https://gitlab.com/search?group_id=6593371&scope=blobs&search=dark_icon_file_name

```
If icon is not specified a generic tool icon will be used.

An additional property `self.dark_icon_file_name` may be specified to provide an alternate icon for
dark window themes.  If this property is not present, the icon specified in `icon_file_name` will
be used when the dark theme is active;

```
A fix would be to add the last two lines below to plugin.py at line 53:
```
        self.icon_file_name = os.path.join(
            os.path.dirname(__file__), 'icon.png')
        self.dark_icon_file_name = os.path.join(
            os.path.dirname(__file__), 'icon.png')
```

**Comment by PatrickFranken** [comment]
Thanks for the report including the actual solution to this :) Will be included in the next release.
