### ISSUE TITLE
Export doesn't support the “Exclude from BOM” and “Exclude from position files” options

### ISSUE THREAD

**Issue by rhard** [AislerHQ/PushForKiCad#17]
Please support the above-mentioned options so the BOM will not be populated with unneeded components. You can check the JLC repository for a solution: https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/master/plugins/process.py

```python
 if not footprint.GetAttributes() & pcbnew.FP_EXCLUDE_FROM_POS_FILES:
```

```python
 if not footprint.GetAttributes() & pcbnew.FP_EXCLUDE_FROM_BOM:
```

![image](https://user-images.githubusercontent.com/8452952/196631342-93f16a5e-1cfc-42af-8733-7dd9b3726866.png)

**Comment by PatrickFranken** [comment]
Valid point! Just solved it in https://github.com/AislerHQ/PushForKiCad/commit/9f3361b1aaff9d1d2f71de553698ce58cd463fe4 We will publish an updated version later today. This change still requires an update to our BOM tool which will happen later this week.
