### ISSUE TITLE
Plugin crashes with KiCad 6 and release 0.13 on windows 10

### ISSUE THREAD

**Issue by calm4git** [AislerHQ/PushForKiCad#2]
While uploading a Board with KiCad6 and 0.13 of the Plugin the process stopps half way. After opening the python console a few error messages will pop up, see screenshot.

![grafik](https://user-images.githubusercontent.com/35043090/149382579-4f3e9c34-d5a1-48d1-8e06-7391a20a2e8f.png)

If you have any further questions, please ask and i'll try to assist. The project that causes this problem can be found at : https://github.com/calm4git/210043-CO2-Guard

Regards

CalM

**Comment by PatrickFranken** [comment]
This issue is caused by an empty title on the drawing frame. We solved this on our end now, so this issue is solved. However it is also recommended to set a title on the drawing frame as this title is transmitted to us and is later applied to the project to.
