### ISSUE TITLE
Not working with KiCad 7, getting progress -1

### ISSUE THREAD

**Issue by martin-vitek** [AislerHQ/PushForKiCad#20]
I'm having trouble uploading some boards. I have created 6 boards. I have successfully pushed 3 simple ones, but I cannot push the remaining 3 complex ones. I'm using `kicad-7.0.0-0.5.rc2.fc37` from Copr.

Script is hanging in the `while progress < 100:` loop in `push_thread.py`, after upload. First iteration returns `progress` 30, but in the following -1 is returned, and the loop is indefinitely hanging.

**Comment by PatrickFranken** [comment]
Could you just give it another try? Our service had some issues just at the time you created the issue. If it's still not working, we'll have close look.

**Comment by martin-vitek** [comment]
It's working now. Thanks.
