### ISSUE TITLE
plugin does not respect "exclude from bom"

### ISSUE THREAD

**Issue by Fuzzlix** [AislerHQ/PushForKiCad#21]
some parts are set as "exclude from bom" in eeschema but are included in the uploaded part list. This includes in my case:
- manual placed footprints like Silkscreen graphics (set as exclude from BOM)
- TC2050 connector (set as exclude from BOM)
- a footprint defining the board outline (set as exclude from BOM)
- ...

**Comment by PatrickFranken** [comment]
We actually  make use of the Not in BOM flag, see https://github.com/AislerHQ/PushForKiCad/blob/main/src/push_thread.py#L113
However we we still import the parts but mark them as do not place during import.

**Comment by Fuzzlix** [comment]
> We actually make use of the Not in BOM flag, see https://github.com/AislerHQ/PushForKiCad/blob/main/src/push_thread.py#L113 However we we still import the parts but mark them as do not place during import.

Semms not to work like expected. What do you think about MPN == "DNP" will be automatically handled as "do not populate" ?

**Comment by PatrickFranken** [comment]
Just doubled checked, if Not in BOM is used it will show up as "excluded" on the BOM after import. Could you send a mail to hello@aisler.net with the file attache? Or if it is not confidential, just attach it right here.
