### ISSUE TITLE
"Page not found" error when renaming project

### ISSUE THREAD

**Issue by bullestock** [AislerHQ/PushForKiCad#24]
I don't know if this is a bug in the plugin or in the Aisler website, but anyway:

1. Click the Aisler Push button in PcbNew
2. On the website, click the pencil icon to edit the project name
3. Enter a new name, click OK
4. You are redirected to https://aisler.net/dead-end

If you now do a Push again, the project does have the new name.

**Comment by tbolender** [comment]
Thanks for reporting the issue, we fixed it!
