### ISSUE TITLE
Pushing the same PCB twice will crash the Plugin (KiCad 6 and Win10)

### ISSUE THREAD

**Issue by calm4git** [AislerHQ/PushForKiCad#3]
Pushing a PCB for the second time with a AISLER Project ID already set in the PCB as comment 4 will crash the Plugin. 

![grafik](https://user-images.githubusercontent.com/35043090/149487851-e5a8c356-fa98-4994-b6f9-1cfc51306d34.png)

![grafik](https://user-images.githubusercontent.com/35043090/149488037-9af465f3-5ed5-47f2-9efe-9ef80cd38f04.png)

Best Regards

CalM

**Comment by tbolender** [comment]
Thanks for your report @calm4git! We had indeed today some service issues leading to errors on upload. They are fixed by now and upload is working again. Feel free to open the issue again if the problem persists.
