### ISSUE TITLE
[Readme] Install from official repository

### ISSUE THREAD

**Issue by cbenhagen** [AislerHQ/PushForKiCad#5]
It would be nice if the plugin could be installed and updated through the official repository.

**Comment by cbenhagen** [comment]
Oh wow, I was too quick with opening this issue after reading the readme. The plugin is already in the repo. I guess all there is left to do is adjust the install instructions. Sorry for the noise.

**Comment by PatrickFranken** [comment]
Just added a hint to the official KiCad repo to the readme. Thanks for the input!
